### ISSUE TITLE
mac 上可以安装么

### ISSUE THREAD

**Issue by stayliv3** [wilson9x1/fenghuangscanner_v3#1]
安装一些模块的时候会报错，不知道是否在mac上测试过~~谢谢~是否可以分享一下安装指南~

**Comment by wilson9x1** [comment]
我就是安装在mac上面的，你安装那个模块报错了，发出看看

**Comment by stayliv3** [comment]
搞到kali里跑起来了~感谢~~

**Comment by wolyty** [comment]
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from factorys.pluginFactory import *
  File "/private/tmp/fenghuangscanner_v3/factorys/pluginFactory.py", line 9, in <module>
    from plugins.smb import *
  File "/private/tmp/fenghuangscanner_v3/plugins/smb.py", line 5, in <module>
    from impacket.smbconnection import *
ImportError: No module named impacket.smbconnection

**Comment by wilson9x1** [comment]
impacket 库没安装
